INSERT INTO comuna (id, nombre) VALUES (1, 'HUALPÉN');
INSERT INTO comuna (id, nombre) VALUES (2, 'ALTO BIOBíO');
INSERT INTO comuna (id, nombre) VALUES (3, 'CHOLCHOL');
INSERT INTO comuna (id, nombre) VALUES (4, 'ALTO HOSPICIO');
INSERT INTO comuna (id, nombre) VALUES (5, 'ALGARROBO');
INSERT INTO comuna (id, nombre) VALUES (6, 'ALHUE');
INSERT INTO comuna (id, nombre) VALUES (7, 'ALTO DEL CARMEN');
INSERT INTO comuna (id, nombre) VALUES (8, 'ANCUD');
INSERT INTO comuna (id, nombre) VALUES (9, 'ANDACOLLO');
INSERT INTO comuna (id, nombre) VALUES (10, 'ANGOL');
INSERT INTO comuna (id, nombre) VALUES (11, 'ANTARTICA');
INSERT INTO comuna (id, nombre) VALUES (12, 'ANTOFAGASTA');
INSERT INTO comuna (id, nombre) VALUES (13, 'ANTUCO');
INSERT INTO comuna (id, nombre) VALUES (14, 'ARAUCO');
INSERT INTO comuna (id, nombre) VALUES (15, 'ARICA');
INSERT INTO comuna (id, nombre) VALUES (16, 'AYSEN');
INSERT INTO comuna (id, nombre) VALUES (17, 'BUIN');
INSERT INTO comuna (id, nombre) VALUES (18, 'BULNES');
INSERT INTO comuna (id, nombre) VALUES (19, 'CABILDO');
INSERT INTO comuna (id, nombre) VALUES (20, 'CABRERO');
INSERT INTO comuna (id, nombre) VALUES (21, 'CALAMA');
INSERT INTO comuna (id, nombre) VALUES (22, 'CALBUCO');
INSERT INTO comuna (id, nombre) VALUES (23, 'CALDERA');
INSERT INTO comuna (id, nombre) VALUES (24, 'CALERA');
INSERT INTO comuna (id, nombre) VALUES (25, 'CALERA DE TANGO');
INSERT INTO comuna (id, nombre) VALUES (26, 'CALLE LARGA');
INSERT INTO comuna (id, nombre) VALUES (27, 'CAMARONES');
INSERT INTO comuna (id, nombre) VALUES (28, 'CAMIÑA');
INSERT INTO comuna (id, nombre) VALUES (29, 'CANELA');
INSERT INTO comuna (id, nombre) VALUES (30, 'CARAHUE');
INSERT INTO comuna (id, nombre) VALUES (31, 'CARTAGENA');
INSERT INTO comuna (id, nombre) VALUES (32, 'CASABLANCA');
INSERT INTO comuna (id, nombre) VALUES (33, 'CASTRO');
INSERT INTO comuna (id, nombre) VALUES (34, 'CATEMU');
INSERT INTO comuna (id, nombre) VALUES (35, 'CAUQUENES');
INSERT INTO comuna (id, nombre) VALUES (36, 'CAÑETE');
INSERT INTO comuna (id, nombre) VALUES (37, 'CERRILLOS');
INSERT INTO comuna (id, nombre) VALUES (38, 'CERRO NAVIA');
INSERT INTO comuna (id, nombre) VALUES (39, 'CHAITEN');
INSERT INTO comuna (id, nombre) VALUES (40, 'CHANCO');
INSERT INTO comuna (id, nombre) VALUES (41, 'CHAÑARAL');
INSERT INTO comuna (id, nombre) VALUES (42, 'CHEPICA');
INSERT INTO comuna (id, nombre) VALUES (43, 'CHIGUAYANTE');
INSERT INTO comuna (id, nombre) VALUES (44, 'CHILE CHICO');
INSERT INTO comuna (id, nombre) VALUES (45, 'CHILLAN');
INSERT INTO comuna (id, nombre) VALUES (46, 'CHILLAN VIEJO');
INSERT INTO comuna (id, nombre) VALUES (47, 'CHIMBARONGO');
INSERT INTO comuna (id, nombre) VALUES (48, 'CHONCHI');
INSERT INTO comuna (id, nombre) VALUES (49, 'CISNES');
INSERT INTO comuna (id, nombre) VALUES (50, 'COBQUECURA');
INSERT INTO comuna (id, nombre) VALUES (51, 'COCHAMO');
INSERT INTO comuna (id, nombre) VALUES (52, 'COCHRANE');
INSERT INTO comuna (id, nombre) VALUES (53, 'CODEGUA');
INSERT INTO comuna (id, nombre) VALUES (54, 'COELEMU');
INSERT INTO comuna (id, nombre) VALUES (55, 'COIHUECO');
INSERT INTO comuna (id, nombre) VALUES (56, 'COINCO');
INSERT INTO comuna (id, nombre) VALUES (57, 'COLBUN');
INSERT INTO comuna (id, nombre) VALUES (58, 'COLCHANE');
INSERT INTO comuna (id, nombre) VALUES (59, 'COLINA');
INSERT INTO comuna (id, nombre) VALUES (60, 'COLLIPULLI');
INSERT INTO comuna (id, nombre) VALUES (61, 'COLTAUCO');
INSERT INTO comuna (id, nombre) VALUES (62, 'COMBARBALA');
INSERT INTO comuna (id, nombre) VALUES (63, 'CONCEPCION');
INSERT INTO comuna (id, nombre) VALUES (64, 'CONCHALI');
INSERT INTO comuna (id, nombre) VALUES (65, 'CONCON');
INSERT INTO comuna (id, nombre) VALUES (66, 'CONSTITUCION');
INSERT INTO comuna (id, nombre) VALUES (67, 'CONTULMO');
INSERT INTO comuna (id, nombre) VALUES (68, 'COPIAPO');
INSERT INTO comuna (id, nombre) VALUES (69, 'COQUIMBO');
INSERT INTO comuna (id, nombre) VALUES (70, 'CORONEL');
INSERT INTO comuna (id, nombre) VALUES (71, 'CORRAL');
INSERT INTO comuna (id, nombre) VALUES (72, 'COYHAIQUE');
INSERT INTO comuna (id, nombre) VALUES (73, 'CUNCO');
INSERT INTO comuna (id, nombre) VALUES (74, 'CURACAUTIN');
INSERT INTO comuna (id, nombre) VALUES (75, 'CURACAVI');
INSERT INTO comuna (id, nombre) VALUES (76, 'CURACO DE VELEZ');
INSERT INTO comuna (id, nombre) VALUES (77, 'CURANILAHUE');
INSERT INTO comuna (id, nombre) VALUES (78, 'CURARREHUE');
INSERT INTO comuna (id, nombre) VALUES (79, 'CUREPTO');
INSERT INTO comuna (id, nombre) VALUES (80, 'CURICO');
INSERT INTO comuna (id, nombre) VALUES (81, 'DALCAHUE');
INSERT INTO comuna (id, nombre) VALUES (82, 'DIEGO DE ALMAGRO');
INSERT INTO comuna (id, nombre) VALUES (83, 'DOÑIHUE');
INSERT INTO comuna (id, nombre) VALUES (84, 'EL BOSQUE');
INSERT INTO comuna (id, nombre) VALUES (85, 'EL CARMEN');
INSERT INTO comuna (id, nombre) VALUES (86, 'EL MONTE');
INSERT INTO comuna (id, nombre) VALUES (87, 'EL QUISCO');
INSERT INTO comuna (id, nombre) VALUES (88, 'EL TABO');
INSERT INTO comuna (id, nombre) VALUES (89, 'EMPEDRADO');
INSERT INTO comuna (id, nombre) VALUES (90, 'ERCILLA');
INSERT INTO comuna (id, nombre) VALUES (91, 'ESTACION CENTRAL');
INSERT INTO comuna (id, nombre) VALUES (92, 'FLORIDA');
INSERT INTO comuna (id, nombre) VALUES (93, 'FREIRE');
INSERT INTO comuna (id, nombre) VALUES (94, 'FREIRINA');
INSERT INTO comuna (id, nombre) VALUES (95, 'FRESIA');
INSERT INTO comuna (id, nombre) VALUES (96, 'FRUTILLAR');
INSERT INTO comuna (id, nombre) VALUES (97, 'FUTALEUFU');
INSERT INTO comuna (id, nombre) VALUES (98, 'FUTRONO');
INSERT INTO comuna (id, nombre) VALUES (99, 'GALVARINO');
INSERT INTO comuna (id, nombre) VALUES (100, 'GENERAL LAGOS');
INSERT INTO comuna (id, nombre) VALUES (101, 'GORBEA');
INSERT INTO comuna (id, nombre) VALUES (102, 'GRANEROS');
INSERT INTO comuna (id, nombre) VALUES (103, 'GUAITECAS');
INSERT INTO comuna (id, nombre) VALUES (104, 'HIJUELAS');
INSERT INTO comuna (id, nombre) VALUES (105, 'HUALAIHUE');
INSERT INTO comuna (id, nombre) VALUES (106, 'HUALAÑE');
INSERT INTO comuna (id, nombre) VALUES (107, 'HUALQUI');
INSERT INTO comuna (id, nombre) VALUES (108, 'HUARA');
INSERT INTO comuna (id, nombre) VALUES (109, 'HUASCO');
INSERT INTO comuna (id, nombre) VALUES (110, 'HUECHURABA');
INSERT INTO comuna (id, nombre) VALUES (111, 'ILLAPEL');
INSERT INTO comuna (id, nombre) VALUES (112, 'INDEPENDENCIA');
INSERT INTO comuna (id, nombre) VALUES (113, 'IQUIQUE');
INSERT INTO comuna (id, nombre) VALUES (114, 'ISLA DE MAIPO');
INSERT INTO comuna (id, nombre) VALUES (115, 'ISLA DE PASCUA');
INSERT INTO comuna (id, nombre) VALUES (116, 'JUAN FERNANDEZ');
INSERT INTO comuna (id, nombre) VALUES (117, 'LA CISTERNA'); -- ¡Corregido aquí!
INSERT INTO comuna (id, nombre) VALUES (118, 'LA CRUZ');
INSERT INTO comuna (id, nombre) VALUES (119, 'LA ESTRELLA');
INSERT INTO comuna (id, nombre) VALUES (120, 'LA FLORIDA');
INSERT INTO comuna (id, nombre) VALUES (121, 'LA GRANJA');
INSERT INTO comuna (id, nombre) VALUES (122, 'LA HIGUERA');
INSERT INTO comuna (id, nombre) VALUES (123, 'LA LIGUA');
INSERT INTO comuna (id, nombre) VALUES (124, 'LA PINTANA');
INSERT INTO comuna (id, nombre) VALUES (125, 'LA REINA');
INSERT INTO comuna (id, nombre) VALUES (126, 'LA SERENA');
INSERT INTO comuna (id, nombre) VALUES (127, 'LA UNION');
INSERT INTO comuna (id, nombre) VALUES (128, 'LAGO RANCO');
INSERT INTO comuna (id, nombre) VALUES (129, 'LAGO VERDE');
INSERT INTO comuna (id, nombre) VALUES (130, 'LAGUNA BLANCA');
INSERT INTO comuna (id, nombre) VALUES (131, 'LAJA');
INSERT INTO comuna (id, nombre) VALUES (132, 'LAMPA');
INSERT INTO comuna (id, nombre) VALUES (133, 'LANCO');
INSERT INTO comuna (id, nombre) VALUES (134, 'LAS CABRAS');
INSERT INTO comuna (id, nombre) VALUES (135, 'LAS CONDES');
INSERT INTO comuna (id, nombre) VALUES (136, 'LAUTARO');
INSERT INTO comuna (id, nombre) VALUES (137, 'LEBU');
INSERT INTO comuna (id, nombre) VALUES (138, 'LICANTEN');
INSERT INTO comuna (id, nombre) VALUES (139, 'LIMACHE');
INSERT INTO comuna (id, nombre) VALUES (140, 'LINARES');
INSERT INTO comuna (id, nombre) VALUES (141, 'LITUECHE');
INSERT INTO comuna (id, nombre) VALUES (142, 'LLANQUIHUE');
INSERT INTO comuna (id, nombre) VALUES (143, 'LLAY-LLAY');
INSERT INTO comuna (id, nombre) VALUES (144, 'LO BARNECHEA');
INSERT INTO comuna (id, nombre) VALUES (145, 'LO ESPEJO');
INSERT INTO comuna (id, nombre) VALUES (146, 'LO PRADO');
INSERT INTO comuna (id, nombre) VALUES (147, 'LOLOL');
INSERT INTO comuna (id, nombre) VALUES (148, 'LONCOCHE');
INSERT INTO comuna (id, nombre) VALUES (149, 'LONGAVI');
INSERT INTO comuna (id, nombre) VALUES (150, 'LONQUIMAY');
INSERT INTO comuna (id, nombre) VALUES (151, 'LOS ALAMOS');
INSERT INTO comuna (id, nombre) VALUES (152, 'LOS ANDES');
INSERT INTO comuna (id, nombre) VALUES (153, 'LOS ANGELES');
INSERT INTO comuna (id, nombre) VALUES (154, 'LOS LAGOS');
INSERT INTO comuna (id, nombre) VALUES (155, 'LOS MUERMOS');
INSERT INTO comuna (id, nombre) VALUES (156, 'LOS SAUCES');
INSERT INTO comuna (id, nombre) VALUES (157, 'LOS VILOS');
INSERT INTO comuna (id, nombre) VALUES (158, 'LOTA');
INSERT INTO comuna (id, nombre) VALUES (159, 'LUMACO');
INSERT INTO comuna (id, nombre) VALUES (160, 'MACHALI');
INSERT INTO comuna (id, nombre) VALUES (161, 'MACUL');
INSERT INTO comuna (id, nombre) VALUES (162, 'MAFIL');
INSERT INTO comuna (id, nombre) VALUES (163, 'MAIPU');
INSERT INTO comuna (id, nombre) VALUES (164, 'MALLOA');
INSERT INTO comuna (id, nombre) VALUES (165, 'MARCHIGUE');
INSERT INTO comuna (id, nombre) VALUES (166, 'MARIA ELENA');
INSERT INTO comuna (id, nombre) VALUES (167, 'MARIA PINTO');
INSERT INTO comuna (id, nombre) VALUES (168, 'MARIQUINA');
INSERT INTO comuna (id, nombre) VALUES (169, 'MAULE');
INSERT INTO comuna (id, nombre) VALUES (170, 'MAULLIN');
INSERT INTO comuna (id, nombre) VALUES (171, 'MEJILLONES');
INSERT INTO comuna (id, nombre) VALUES (172, 'MELIPEUCO');
INSERT INTO comuna (id, nombre) VALUES (173, 'MELIPILLA');
INSERT INTO comuna (id, nombre) VALUES (174, 'MOLINA');
INSERT INTO comuna (id, nombre) VALUES (175, 'MONTE PATRIA');
INSERT INTO comuna (id, nombre) VALUES (176, 'MOSTAZAL');
INSERT INTO comuna (id, nombre) VALUES (177, 'MULCHEN');
INSERT INTO comuna (id, nombre) VALUES (178, 'NACIMIENTO');
INSERT INTO comuna (id, nombre) VALUES (179, 'NANCAGUA');
INSERT INTO comuna (id, nombre) VALUES (180, 'NATALES');
INSERT INTO comuna (id, nombre) VALUES (181, 'CABO DE HORNOS');
INSERT INTO comuna (id, nombre) VALUES (182, 'NAVIDAD');
INSERT INTO comuna (id, nombre) VALUES (183, 'NEGRETE');
INSERT INTO comuna (id, nombre) VALUES (184, 'NINHUE');
INSERT INTO comuna (id, nombre) VALUES (185, 'NOGALES');
INSERT INTO comuna (id, nombre) VALUES (186, 'NUEVA IMPERIAL');
INSERT INTO comuna (id, nombre) VALUES (187, 'O''Higgins');
INSERT INTO comuna (id, nombre) VALUES (188, 'OLIVAR');
INSERT INTO comuna (id, nombre) VALUES (189, 'OLLAGUE');
INSERT INTO comuna (id, nombre) VALUES (190, 'OLMUE');
INSERT INTO comuna (id, nombre) VALUES (191, 'OSORNO');
INSERT INTO comuna (id, nombre) VALUES (192, 'OVALLE');
INSERT INTO comuna (id, nombre) VALUES (193, 'PADRE HURTADO');
INSERT INTO comuna (id, nombre) VALUES (194, 'PADRE LAS CASAS');
INSERT INTO comuna (id, nombre) VALUES (195, 'PAIHUANO');
INSERT INTO comuna (id, nombre) VALUES (196, 'PAILLACO');
INSERT INTO comuna (id, nombre) VALUES (197, 'PAINE');
INSERT INTO comuna (id, nombre) VALUES (198, 'PALENA');
INSERT INTO comuna (id, nombre) VALUES (199, 'PALMILLA');
INSERT INTO comuna (id, nombre) VALUES (200, 'PANGUIPULLI');
INSERT INTO comuna (id, nombre) VALUES (201, 'PANQUEHUE');
INSERT INTO comuna (id, nombre) VALUES (202, 'PAPUDO');
INSERT INTO comuna (id, nombre) VALUES (203, 'PAREDONES');
INSERT INTO comuna (id, nombre) VALUES (204, 'PARRAL');
INSERT INTO comuna (id, nombre) VALUES (205, 'PEDRO AGUIRRE CERDA');
INSERT INTO comuna (id, nombre) VALUES (206, 'PELARCO');
INSERT INTO comuna (id, nombre) VALUES (207, 'PELLUHUE');
INSERT INTO comuna (id, nombre) VALUES (208, 'PEMUCO');
INSERT INTO comuna (id, nombre) VALUES (209, 'PENCAHUE');
INSERT INTO comuna (id, nombre) VALUES (210, 'PENCO');
INSERT INTO comuna (id, nombre) VALUES (211, 'PERALILLO');
INSERT INTO comuna (id, nombre) VALUES (212, 'PERQUENCO');
INSERT INTO comuna (id, nombre) VALUES (213, 'PETORCA');
INSERT INTO comuna (id, nombre) VALUES (214, 'PEUMO');
INSERT INTO comuna (id, nombre) VALUES (215, 'PEÑAFLOR');
INSERT INTO comuna (id, nombre) VALUES (216, 'PEÑALOLEN');
INSERT INTO comuna (id, nombre) VALUES (217, 'PICA');
INSERT INTO comuna (id, nombre) VALUES (218, 'PICHIDEGUA');
INSERT INTO comuna (id, nombre) VALUES (219, 'PICHILEMU');
INSERT INTO comuna (id, nombre) VALUES (220, 'PINTO');
INSERT INTO comuna (id, nombre) VALUES (221, 'PIRQUE');
INSERT INTO comuna (id, nombre) VALUES (222, 'PITRUFQUEN');
INSERT INTO comuna (id, nombre) VALUES (223, 'PLACILLA');
INSERT INTO comuna (id, nombre) VALUES (224, 'PORTEZUELO');
INSERT INTO comuna (id, nombre) VALUES (225, 'PORVENIR');
INSERT INTO comuna (id, nombre) VALUES (226, 'POZO ALMONTE');
INSERT INTO comuna (id, nombre) VALUES (227, 'PRIMAVERA');
INSERT INTO comuna (id, nombre) VALUES (228, 'PROVIDENCIA');
INSERT INTO comuna (id, nombre) VALUES (229, 'PUCHUNCAVI');
INSERT INTO comuna (id, nombre) VALUES (231, 'PUDAHUEL');
INSERT INTO comuna (id, nombre) VALUES (233, 'PUERTO MONTT');
INSERT INTO comuna (id, nombre) VALUES (234, 'PUERTO OCTAY');
INSERT INTO comuna (id, nombre) VALUES (235, 'PUERTO VARAS');
INSERT INTO comuna (id, nombre) VALUES (237, 'PUNITAQUI');
INSERT INTO comuna (id, nombre) VALUES (238, 'PUNTA ARENAS');
INSERT INTO comuna (id, nombre) VALUES (239, 'PUQUELDON');
INSERT INTO comuna (id, nombre) VALUES (241, 'PURRANQUE');
INSERT INTO comuna (id, nombre) VALUES (243, 'PUTRE');
INSERT INTO comuna (id, nombre) VALUES (244, 'PUYEHUE');
INSERT INTO comuna (id, nombre) VALUES (246, 'QUELLON');
INSERT INTO comuna (id, nombre) VALUES (247, 'QUEMCHI');
INSERT INTO comuna (id, nombre) VALUES (249, 'QUILICURA');
INSERT INTO comuna (id, nombre) VALUES (250, 'QUILLECO');
INSERT INTO comuna (id, nombre) VALUES (252, 'QUILLOTA');
INSERT INTO comuna (id, nombre) VALUES (253, 'QUILPUE');
INSERT INTO comuna (id, nombre) VALUES (254, 'QUINCHAO');
INSERT INTO comuna (id, nombre) VALUES (256, 'QUINTA NORMAL');
INSERT INTO comuna (id, nombre) VALUES (257, 'QUINTERO');
INSERT INTO comuna (id, nombre) VALUES (258, 'QUIRIHUE');
INSERT INTO comuna (id, nombre) VALUES (259, 'RANCAGUA');
INSERT INTO comuna (id, nombre) VALUES (261, 'RAUCO');
INSERT INTO comuna (id, nombre) VALUES (262, 'RECOLETA');
INSERT INTO comuna (id, nombre) VALUES (263, 'RENAICO');
INSERT INTO comuna (id, nombre) VALUES (265, 'RENGO');
INSERT INTO comuna (id, nombre) VALUES (267, 'RETIRO');
INSERT INTO comuna (id, nombre) VALUES (268, 'RINCONADA');
INSERT INTO comuna (id, nombre) VALUES (269, 'RIO BUENO');
INSERT INTO comuna (id, nombre) VALUES (271, 'RIO HURTADO');
INSERT INTO comuna (id, nombre) VALUES (272, 'RIO IBAÑEZ');
INSERT INTO comuna (id, nombre) VALUES (274, 'RIO VERDE');
INSERT INTO comuna (id, nombre) VALUES (275, 'ROMERAL');
INSERT INTO comuna (id, nombre) VALUES (276, 'SAAVEDRA');
INSERT INTO comuna (id, nombre) VALUES (278, 'SALAMANCA');
INSERT INTO comuna (id, nombre) VALUES (279, 'SAN ANTONIO');
INSERT INTO comuna (id, nombre) VALUES (280, 'SAN BERNARDO');
INSERT INTO comuna (id, nombre) VALUES (281, 'SAN CARLOS');
INSERT INTO comuna (id, nombre) VALUES (283, 'SAN ESTEBAN');
INSERT INTO comuna (id, nombre) VALUES (284, 'SAN FABIAN');
INSERT INTO comuna (id, nombre) VALUES (285, 'SAN FELIPE');
INSERT INTO comuna (id, nombre) VALUES (287, 'SAN GREGORIO');
INSERT INTO comuna (id, nombre) VALUES (288, 'SAN IGNACIO');
INSERT INTO comuna (id, nombre) VALUES (289, 'SAN JAVIER');
INSERT INTO comuna (id, nombre) VALUES (290, 'SAN JOAQUIN');
INSERT INTO comuna (id, nombre) VALUES (292, 'SAN JUAN DE LA COSTA');
INSERT INTO comuna (id, nombre) VALUES (293, 'SAN MIGUEL');
INSERT INTO comuna (id, nombre) VALUES (294, 'SAN NICOLAS');
INSERT INTO comuna (id, nombre) VALUES (295, 'SAN PABLO');
INSERT INTO comuna (id, nombre) VALUES (297, 'SAN PEDRO DE ATACAMA');
INSERT INTO comuna (id, nombre) VALUES (298, 'SAN PEDRO DE LA PAZ');
INSERT INTO comuna (id, nombre) VALUES (299, 'SAN RAFAEL');
INSERT INTO comuna (id, nombre) VALUES (301, 'SAN ROSENDO');
INSERT INTO comuna (id, nombre) VALUES (302, 'SAN VICENTE');
INSERT INTO comuna (id, nombre) VALUES (304, 'SANTA CRUZ');
INSERT INTO comuna (id, nombre) VALUES (305, 'SANTA JUANA');
INSERT INTO comuna (id, nombre) VALUES (306, 'SANTA MARIA');
INSERT INTO comuna (id, nombre) VALUES (307, 'SANTIAGO');
INSERT INTO comuna (id, nombre) VALUES (309, 'SIERRA GORDA');
INSERT INTO comuna (id, nombre) VALUES (310, 'TALAGANTE');
INSERT INTO comuna (id, nombre) VALUES (311, 'TALCA');
INSERT INTO comuna (id, nombre) VALUES (313, 'TALTAL');
INSERT INTO comuna (id, nombre) VALUES (314, 'TEMUCO');
INSERT INTO comuna (id, nombre) VALUES (315, 'TENO');
INSERT INTO comuna (id, nombre) VALUES (316, 'TEODORO SCHMIDT');
INSERT INTO comuna (id, nombre) VALUES (318, 'TILTIL');
INSERT INTO comuna (id, nombre) VALUES (319, 'TIMAUKEL');
INSERT INTO comuna (id, nombre) VALUES (320, 'TIRUA');
INSERT INTO comuna (id, nombre) VALUES (321, 'TOCOPILLA');
INSERT INTO comuna (id, nombre) VALUES (323, 'TOME');
INSERT INTO comuna (id, nombre) VALUES (324, 'TORRES DEL PAINE');
INSERT INTO comuna (id, nombre) VALUES (326, 'TRAIGUEN');
INSERT INTO comuna (id, nombre) VALUES (328, 'TUCAPEL');
INSERT INTO comuna (id, nombre) VALUES (329, 'VALDIVIA');
INSERT INTO comuna (id, nombre) VALUES (330, 'VALLENAR');
INSERT INTO comuna (id, nombre) VALUES (332, 'VICHUQUEN');
INSERT INTO comuna (id, nombre) VALUES (333, 'VICTORIA');
INSERT INTO comuna (id, nombre) VALUES (334, 'VICUÑA');
INSERT INTO comuna (id, nombre) VALUES (336, 'VILLA ALEGRE');
INSERT INTO comuna (id, nombre) VALUES (338, 'VILLARRICA');
INSERT INTO comuna (id, nombre) VALUES (339, 'VITACURA');
INSERT INTO comuna (id, nombre) VALUES (340, 'VIÑA DEL MAR');
INSERT INTO comuna (id, nombre) VALUES (341, 'YERBAS BUENAS');
INSERT INTO comuna (id, nombre) VALUES (343, 'YUNGAY');
INSERT INTO comuna (id, nombre) VALUES (344, 'ZAPALLAR');
INSERT INTO comuna (id, nombre) VALUES (346, 'ÑUÑOA');
INSERT INTO comuna (id, nombre) VALUES (230, 'PUCON');
INSERT INTO comuna (id, nombre) VALUES (232, 'PUENTE ALTO');
INSERT INTO comuna (id, nombre) VALUES (236, 'PUMANQUE');
INSERT INTO comuna (id, nombre) VALUES (240, 'PUREN');
INSERT INTO comuna (id, nombre) VALUES (242, 'PUTAENDO');
INSERT INTO comuna (id, nombre) VALUES (245, 'QUEILEN');
INSERT INTO comuna (id, nombre) VALUES (248, 'QUILACO');
INSERT INTO comuna (id, nombre) VALUES (251, 'QUILLON');
INSERT INTO comuna (id, nombre) VALUES (255, 'QUINTA DE TILCOCO');
INSERT INTO comuna (id, nombre) VALUES (260, 'RANQUIL');
INSERT INTO comuna (id, nombre) VALUES (264, 'RENCA');
INSERT INTO comuna (id, nombre) VALUES (266, 'REQUINOA');
INSERT INTO comuna (id, nombre) VALUES (270, 'RIO CLARO');
INSERT INTO comuna (id, nombre) VALUES (273, 'RIO NEGRO');
INSERT INTO comuna (id, nombre) VALUES (277, 'SAGRADA FAMILIA');
INSERT INTO comuna (id, nombre) VALUES (282, 'SAN CLEMENTE');
INSERT INTO comuna (id, nombre) VALUES (286, 'SAN FERNANDO');
INSERT INTO comuna (id, nombre) VALUES (291, 'SAN JOSE DE MAIPO');
INSERT INTO comuna (id, nombre) VALUES (296, 'SAN PEDRO');
INSERT INTO comuna (id, nombre) VALUES (300, 'SAN RAMON');
INSERT INTO comuna (id, nombre) VALUES (303, 'SANTA BARBARA');
INSERT INTO comuna (id, nombre) VALUES (308, 'SANTO DOMINGO');
INSERT INTO comuna (id, nombre) VALUES (312, 'TALCAHUANO');
INSERT INTO comuna (id, nombre) VALUES (317, 'TIERRA AMARILLA');
INSERT INTO comuna (id, nombre) VALUES (322, 'TOLTEN');
INSERT INTO comuna (id, nombre) VALUES (325, 'TORTEL');
INSERT INTO comuna (id, nombre) VALUES (327, 'TREGUACO');
INSERT INTO comuna (id, nombre) VALUES (331, 'VALPARAISO');
INSERT INTO comuna (id, nombre) VALUES (335, 'VILCUN');
INSERT INTO comuna (id, nombre) VALUES (337, 'VILLA ALEMANA');
INSERT INTO comuna (id, nombre) VALUES (342, 'YUMBEL');
INSERT INTO comuna (id, nombre) VALUES (345, 'ÑIQUEN');